import sqlite3

# Connessione al database
conn = sqlite3.connect("planner.db")
cursor = conn.cursor()

# Creazione della tabella per le ricette
cursor.execute("""
CREATE TABLE IF NOT EXISTS ricette (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    categoria TEXT NOT NULL,  -- Es. "vegano", "vegetariano", ecc.
    ingredienti TEXT NOT NULL -- Lista di ingredienti separati da virgole
);
""")

# Creazione della tabella per il piano settimanale
cursor.execute("""
CREATE TABLE IF NOT EXISTS piano_settimanale (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    giorno TEXT NOT NULL,       -- Es. "Lunedì", "Martedì", ecc.
    pasto TEXT NOT NULL,        -- Es. "Colazione", "Pranzo", ecc.
    ricetta_id INTEGER NOT NULL, -- Collega il pasto a una ricetta
    FOREIGN KEY (ricetta_id) REFERENCES ricette(id) ON DELETE CASCADE
);
""")

# Popolamento della tabella ricette con alcune ricette di esempio
ricette_predefinite = [
    ("Pasta al pomodoro", "vegetariano", "pasta integrale, pomodoro, olio extravergine d'oliva"),
    ("Insalata di quinoa", "vegetariano", "quinoa, pomodori, cetrioli, prezzemolo, limone"),
    ("Zuppa di lenticchie", "vegetariano", "lenticchie rosse, cipolla, carota, sedano, curcuma"),
    ("Polpette di zucchine", "vegetariano", "zucchine, pangrattato integrale, parmigiano"),
    ("Frittata di ceci", "vegetariano", "farina di ceci, acqua, zucchine, cipolla"),
    ("Ratatouille", "vegetariano", "melanzane, zucchine, peperoni, pomodori, erbe provenzali"),
    ("Burger di fagioli", "vegetariano", "fagioli neri, avena, cipolla, paprika"),
    ("Crema di carote", "vegetariano", "carote, zenzero, brodo vegetale, olio extravergine d'oliva"),
    ("Insalata di farro", "vegetariano", "farro, pomodorini, olive, basilico"),
    ("Hummus", "vegetariano", "ceci, tahina, limone, aglio, olio extravergine d'oliva"),
    ("Bruschette al pomodoro", "vegetariano", "pane integrale, pomodori, aglio, basilico"),
    ("Vellutata di zucca", "vegetariano", "zucca, patata, brodo vegetale, noce moscata"),
    ("Insalata di spinaci", "vegetariano", "spinaci freschi, noci, mela, aceto balsamico"),
    ("Pasta al pesto", "vegetariano", "pasta integrale, basilico, pinoli, parmigiano, olio"),
    ("Zucchine ripiene", "vegetariano", "zucchine, ricotta, pomodori secchi, erbe aromatiche"),
    ("Tabbouleh", "vegetariano", "bulgur, prezzemolo, menta, limone, pomodorini"),
    ("Piadina vegetariana", "vegetariano", "piadina integrale, hummus, verdure grigliate"),
    ("Melanzane alla parmigiana", "vegetariano", "melanzane, passata di pomodoro, mozzarella, parmigiano"),
    ("Tortino di patate e porri", "vegetariano", "patate, porri, formaggio magro, pangrattato"),
    ("Spiedini di verdure", "vegetariano", "peperoni, zucchine, funghi, cipolla, olio e spezie"),
    ("Gnocchi al pesto di rucola", "vegetariano", "gnocchi di patate, rucola, mandorle, parmigiano, olio"),
    ("Crema di zucchine", "vegetariano", "zucchine, porri, patate, brodo vegetale"),
    ("Polenta con funghi", "vegetariano", "polenta, funghi porcini, aglio, prezzemolo"),
    ("Insalata di cavolo rosso", "vegetariano", "cavolo rosso, carote, mele, aceto di mele"),
    ("Tortino di ceci e spinaci", "vegetariano", "ceci, spinaci, pangrattato integrale, aglio"),
    ("Risotto agli asparagi", "vegetariano", "riso integrale, asparagi, brodo vegetale, scalogno"),
    ("Fagiolini al vapore", "vegetariano", "fagiolini, limone, olio extravergine d'oliva"),
    ("Zuppa di cavolfiore", "vegetariano", "cavolfiore, patate, porri, latte di soia"),
    ("Crocchette di carote", "vegetariano", "carote, patate, pangrattato integrale, prezzemolo"),
    ("Risotto alla zucca", "vegetariano", "riso integrale, zucca, cipolla, brodo vegetale"),
    ("Insalata di ceci", "vegetariano", "ceci, pomodori, cetrioli, cipolla rossa, menta"),
    ("Pasta con broccoli", "vegetariano", "pasta integrale, broccoli, aglio, peperoncino"),
    ("Frittelle di melanzane", "vegetariano", "melanzane, farina integrale, erbe aromatiche, olio"),
    ("Zuppa di verdure", "vegetariano", "carote, zucchine, patate, sedano, brodo vegetale"),
    ("Pizza vegetariana", "vegetariano", "base integrale, pomodoro, mozzarella, verdure grigliate"),
    ("Lasagne vegetariane", "vegetariano", "lasagne integrali, verdure, besciamella vegetale"),
    ("Crema di piselli", "vegetariano", "piselli, menta, brodo vegetale, cipolla"),
    ("Insalata di riso", "vegetariano", "riso integrale, piselli, mais, pomodori, olive"),
    ("Tofu saltato con verdure", "vegetariano", "tofu, carote, zucchine, salsa di soia"),
    ("Insalata di quinoa", "vegano", "quinoa, pomodori, cetrioli, prezzemolo, limone"),
    ("Crema di zucca", "vegano", "zucca, patate, brodo vegetale, zenzero"),
    ("Hummus di ceci", "vegano", "ceci, tahina, limone, aglio, olio extravergine d'oliva"),
    ("Zuppa di lenticchie", "vegano", "lenticchie, cipolla, carote, sedano, cumino"),
    ("Burger di ceci", "vegano", "ceci, avena, prezzemolo, paprika"),
    ("Insalata di farro", "vegano", "farro, pomodorini, rucola, olive, limone"),
    ("Spaghetti di zucchine", "vegano", "zucchine, pomodori secchi, pinoli, basilico"),
    ("Porridge salato", "vegano", "avena, spinaci, funghi, lievito alimentare"),
    ("Vellutata di carote", "vegano", "carote, zenzero, latte di cocco, curcuma"),
    ("Tofu alla piastra", "vegano", "tofu, salsa di soia, zenzero, sesamo"),
    ("Ratatouille", "vegano", "melanzane, zucchine, peperoni, pomodori, timo"),
    ("Zuppa di cavolo nero", "vegano", "cavolo nero, patate, cipolla, brodo vegetale"),
    ("Smoothie bowl", "vegano", "banana, frutti di bosco, latte di mandorla, semi di chia"),
    ("Insalata di ceci", "vegano", "ceci, pomodori, cipolla rossa, cetrioli, menta"),
    ("Polpette di lenticchie", "vegano", "lenticchie, pangrattato integrale, erbe aromatiche"),
    ("Couscous alle verdure", "vegano", "couscous integrale, zucchine, carote, ceci, curcuma"),
    ("Crema di broccoli", "vegano", "broccoli, patate, brodo vegetale, olio extravergine d'oliva"),
    ("Bowl di avocado e chickpeas", "vegano", "avocado, ceci, pomodorini, spinaci, olio extravergine d'oliva"),
    ("Insalata di riso integrale", "vegano", "riso integrale, mais, piselli, peperoni"),
    ("Pasta con crema di avocado", "vegano", "pasta integrale, avocado, limone, basilico"),
    ("Frittelle di ceci", "vegano", "farina di ceci, acqua, spezie, prezzemolo"),
    ("Zuppa di pomodoro", "vegano", "pomodori, cipolla, aglio, basilico"),
    ("Verdure al vapore con salsa tahina", "vegano", "broccoli, carote, cavolfiore, tahina"),
    ("Wrap vegano", "vegano", "tortilla integrale, hummus, verdure grigliate, rucola"),
    ("Risotto alle zucchine", "vegano", "riso integrale, zucchine, brodo vegetale, limone"),
    ("Crema di piselli e menta", "vegano", "piselli, menta, brodo vegetale, olio extravergine d'oliva"),
    ("Insalata di cavolo cappuccio", "vegano", "cavolo cappuccio, carote, aceto di mele, semi di sesamo"),
    ("Chili vegano", "vegano", "fagioli rossi, pomodori, peperoni, spezie"),
    ("Spiedini di verdure", "vegano", "peperoni, zucchine, funghi, melanzane"),
    ("Pasta al pomodoro e basilico", "vegano", "pasta integrale, pomodori freschi, basilico, olio"),
    ("Zuppa di miso", "vegano", "miso, tofu, alga wakame, cipollotto"),
    ("Curry di verdure", "vegano", "latte di cocco, zucchine, carote, curry, ceci"),
    ("Crema di asparagi", "vegano", "asparagi, patate, brodo vegetale, olio extravergine d'oliva"),
    ("Fagiolini saltati", "vegano", "fagiolini, aglio, olio extravergine d'oliva, peperoncino"),
    ("Smoothie proteico", "vegano", "banana, spinaci, proteine vegetali, latte di soia"),
    ("Crocchette di tofu", "vegano", "tofu, patate, pangrattato integrale, erbe aromatiche"),
    ("Zuppa di verdure", "vegano", "zucchine, carote, patate, cipolla, brodo vegetale"),
    ("Insalata di spinaci", "vegano", "spinaci freschi, avocado, semi di girasole, limone"),
    ("Gnocchi di patate con pesto vegano", "vegano", "gnocchi di patate, basilico, pinoli, lievito alimentare"),
    ("Filetto di trota al forno", "senza_lattosio", "trota, limone, aglio, timo"),
    ("Zuppa di ceci", "senza_lattosio", "ceci, carote, cipolla, rosmarino, brodo vegetale"),
    ("Insalata di pollo e avocado", "senza_lattosio", "pollo, avocado, rucola, pomodorini, limone"),
    ("Melanzane grigliate", "senza_lattosio", "melanzane, aglio, prezzemolo, olio extravergine d'oliva"),
    ("Carpaccio di zucchine", "senza_lattosio", "zucchine, limone, olio extravergine d'oliva, pepe"),
    ("Pollo con verdure al vapore", "senza_lattosio", "petto di pollo, zucchine, carote, broccolo"),
    ("Insalata di fagioli cannellini", "senza_lattosio", "fagioli cannellini, cipolla rossa, prezzemolo, limone"),
    ("Orata al cartoccio", "senza_lattosio", "orata, pomodorini, capperi, olive, limone"),
    ("Pasta con gamberi e zucchine", "senza_lattosio", "pasta integrale, gamberi, zucchine, aglio, prezzemolo"),
    ("Crema di zucchine", "senza_lattosio", "zucchine, porri, patate, brodo vegetale"),
    ("Spaghetti di riso con verdure", "senza_lattosio", "spaghetti di riso, carote, peperoni, cipolla, salsa di soia"),
    ("Petto di pollo al limone", "senza_lattosio", "petto di pollo, limone, pepe nero, olio"),
    ("Vellutata di finocchi", "senza_lattosio", "finocchi, patate, brodo vegetale, olio extravergine d'oliva"),
    ("Insalata di bulgur", "senza_lattosio", "bulgur, pomodorini, menta, limone, cetrioli"),
    ("Branzino al forno", "senza_lattosio", "branzino, limone, timo, aglio, pepe"),
    ("Pasta al ragù di verdure", "senza_lattosio", "pasta integrale, melanzane, zucchine, carote, pomodori"),
    ("Tortino di carote", "senza_lattosio", "carote, farina di mandorle, olio di semi, uova"),
    ("Salmone affumicato con insalata", "senza_lattosio", "salmone affumicato, insalata mista, avocado, limone"),
    ("Pollo alla curcuma", "senza_lattosio", "petto di pollo, curcuma, olio, pepe nero"),
    ("Risotto al limone", "senza_lattosio", "riso integrale, limone, brodo vegetale, prezzemolo"),
    ("Cavolfiore gratinato", "senza_lattosio", "cavolfiore, pangrattato, prezzemolo, aglio"),
    ("Gamberi alla piastra", "senza_lattosio", "gamberi, limone, aglio, prezzemolo"),
    ("Crema di carote e zenzero", "senza_lattosio", "carote, zenzero, brodo vegetale, olio extravergine d'oliva"),
    ("Pesce al vapore", "senza_lattosio", "merluzzo, limone, timo, olio extravergine d'oliva"),
    ("Polpette di pollo", "senza_lattosio", "pollo macinato, pangrattato, prezzemolo, spezie"),
    ("Zuppa di verdure e orzo", "senza_lattosio", "orzo, carote, zucchine, sedano, brodo vegetale"),
    ("Insalata di gamberi", "senza_lattosio", "gamberi, lattuga, avocado, pomodorini, limone"),
    ("Pasta con pomodorini e tonno", "senza_lattosio", "pasta integrale, pomodorini, tonno, aglio"),
    ("Riso venere con verdure", "senza_lattosio", "riso venere, zucchine, peperoni, olio extravergine d'oliva"),
    ("Pollo con zucchine", "senza_lattosio", "petto di pollo, zucchine, aglio, pepe"),
    ("Insalata di farro e ceci", "senza_lattosio", "farro, ceci, pomodorini, menta, limone"),
    ("Gnocchi di patate al ragù vegetale", "senza_lattosio", "gnocchi di patate, ragù di verdure, basilico"),
    ("Filetto di pesce con spinaci", "senza_lattosio", "filetto di pesce, spinaci, aglio, olio"),
    ("Frittata di asparagi", "senza_lattosio", "uova, asparagi, olio extravergine d'oliva, pepe"),
    ("Risotto con zucchine", "senza_lattosio", "riso integrale, zucchine, brodo vegetale, scalogno"),
    ("Insalata di spinaci e ceci", "senza_lattosio", "spinaci freschi, ceci, limone, semi di zucca"),
    ("Merluzzo in umido", "senza_lattosio", "merluzzo, pomodorini, aglio, prezzemolo"),
    ("Orzo con carote e piselli", "senza_lattosio", "orzo, carote, piselli, olio extravergine d'oliva"),
    ("Frittelle di zucchine", "senza_lattosio", "zucchine, farina integrale, prezzemolo, olio"),
    ("Polpette di ceci al forno", "gluten free", "ceci, prezzemolo, cumino, farina di riso"),
    ("Frittata di spinaci", "gluten free", "uova, spinaci freschi, aglio, olio extravergine d'oliva"),
    ("Risotto al radicchio", "gluten free", "riso arborio, radicchio, scalogno, brodo vegetale"),
    ("Filetto di pollo alla paprika", "gluten free", "petto di pollo, paprika dolce, olio, pepe"),
    ("Crema di patate dolci", "gluten free", "patate dolci, brodo vegetale, rosmarino, olio"),
    ("Insalata di quinoa e avocado", "gluten free", "quinoa, avocado, pomodorini, limone"),
    ("Carpaccio di barbabietola", "gluten free", "barbabietola, limone, olio extravergine d'oliva, semi di lino"),
    ("Zuppa di zucca e carote", "gluten free", "zucca, carote, zenzero, brodo vegetale"),
    ("Pollo al limone con asparagi", "gluten free", "petto di pollo, limone, asparagi, pepe nero"),
    ("Tortino di riso", "gluten free", "riso integrale, zucchine, parmigiano, uova"),
    ("Cavolfiore al curry", "gluten free", "cavolfiore, curry, olio extravergine d'oliva, semi di cumino"),
    ("Insalata di gamberi e agrumi", "gluten free", "gamberi, arance, finocchi, olio d'oliva"),
    ("Pasta di mais al pesto", "gluten free", "pasta di mais, basilico, pinoli, olio extravergine d'oliva"),
    ("Salmone alla griglia", "gluten free", "salmone, limone, rosmarino, pepe"),
    ("Frittelle di patate", "gluten free", "patate, uova, prezzemolo, olio"),
    ("Risotto ai funghi", "gluten free", "riso, funghi porcini, scalogno, brodo vegetale"),
    ("Bocconcini di tacchino", "gluten free", "tacchino, curcuma, olio, pepe nero"),
    ("Vellutata di zucchine", "gluten free", "zucchine, patate, brodo vegetale, olio"),
    ("Polenta con verdure grigliate", "gluten free", "polenta, peperoni, zucchine, melanzane"),
    ("Zuppa di porri e patate", "gluten free", "porri, patate, brodo vegetale, olio"),
    ("Pancake di banane", "gluten free", "banane, uova, cannella, sciroppo d'acero"),
    ("Insalata di ceci e avocado", "gluten free", "ceci, avocado, pomodorini, limone"),
    ("Pollo al sesamo", "gluten free", "petto di pollo, semi di sesamo, salsa di soia senza glutine"),
    ("Riso venere con gamberi", "gluten free", "riso venere, gamberi, zucchine, olio extravergine d'oliva"),
    ("Zuppa di finocchio e mele", "gluten free", "finocchio, mele, brodo vegetale, pepe"),
    ("Tortilla con hummus", "gluten free", "tortilla di mais, hummus, verdure fresche, rucola"),
    ("Polpette di lenticchie", "gluten free", "lenticchie, farina di mais, prezzemolo, aglio"),
    ("Frittata con zucchine", "gluten free", "uova, zucchine, olio extravergine d'oliva, pepe"),
    ("Pollo alla griglia con insalata di cetrioli e menta", "gluten free", "petto di pollo, cetrioli, menta, limone, olio extravergine d'oliva"),
    ("Pesce spada al forno", "gluten free", "pesce spada, pomodorini, capperi, origano"),
    ("Sformato di verdure", "gluten free", "carote, zucchine, uova, parmigiano"),
    ("Fagiolini al pomodoro", "gluten free", "fagiolini, pomodorini, aglio, olio"),
    ("Zuppa di carciofi", "gluten free", "carciofi, patate, brodo vegetale, limone"),
    ("Filetto di tonno grigliato", "gluten free", "filetto di tonno, aglio, prezzemolo, pepe"),
    ("Spaghetti di riso con gamberi", "gluten free", "spaghetti di riso, gamberi, zucchine, salsa di soia senza glutine"),
    ("Insalata di spinaci e noci", "gluten free", "spinaci freschi, noci, melagrana, aceto balsamico"),
    ("Crocchette di patate e quinoa", "gluten free", "patate, quinoa, prezzemolo, farina di riso"),
    ("Salmone con verdure al forno", "gluten free", "salmone, zucchine, carote, olio extravergine d'oliva"),
    ("Risotto al limone e rosmarino", "gluten free", "riso integrale, limone, rosmarino, brodo vegetale"),
    ("Insalata di riso nero con avocado", "gluten free", "riso nero, avocado, pomodorini, cetriolo, limone"),
    ("Insalata di tonno", "normale", "tonno, fagioli, cipolla rossa, rucola, limone"),
    ("Riso basmati con pollo e verdure", "normale", "riso basmati, pollo, zucchine, peperoni, curry"),
    ("Zuppa di pomodoro e basilico", "normale", "pomodori, cipolla, basilico, brodo vegetale"),
    ("Polpette di melanzane", "normale", "melanzane, uova, parmigiano, pangrattato"),
    ("Tartare di salmone", "normale", "salmone, avocado, lime, cipolla rossa"),
    ("Zuppa di lenticchie", "normale", "lenticchie, carote, cipolla, sedano, brodo vegetale"),
    ("Frittata di zucchine", "normale", "uova, zucchine, cipolla, prezzemolo"),
    ("Tortilla di patate", "normale", "patate, uova, cipolla, olio"),
    ("Pesce al forno con limone", "normale", "filetto di pesce, limone, olio extravergine d'oliva, prezzemolo"),
    ("Insalata mista con pollo", "normale", "insalata mista, pollo, pomodorini, avocado, limone"),
    ("Couscous con verdure grigliate", "normale", "couscous, zucchine, melanzane, peperoni, cipolla"),
    ("Polpette di tacchino", "normale", "tacchino macinato, uovo, pangrattato, prezzemolo"),
    ("Ratatouille", "normale", "melanzane, zucchine, peperoni, pomodori, aglio"),
    ("Filetto di salmone al forno", "normale", "salmone, rosmarino, aglio, limone"),
    ("Risotto ai funghi", "normale", "riso, funghi, brodo vegetale, parmigiano"),
    ("Caponata di melanzane", "normale", "melanzane, pomodori, cipolla, olive, capperi"),
    ("Pollo alla griglia con insalata", "normale", "pollo, insalata, pomodorini, cetrioli, limone"),
    ("Vellutata di piselli", "normale", "piselli, patate, cipolla, brodo vegetale"),
    ("Bistecca alla griglia", "normale", "bistecca, olio extravergine d'oliva, rosmarino, pepe"),
    ("Riso basmati con verdure", "normale", "riso basmati, carote, zucchine, piselli, cipolla"),
    ("Frittelle di carote", "normale", "carote, farina, uova, prezzemolo"),
    ("Zuppa di cavolfiore", "normale", "cavolfiore, patate, brodo vegetale, noce moscata"),
    ("Insalata di farro con pomodorini", "normale", "farro, pomodorini, rucola, limone"),
    ("Pasta con sugo di verdure", "normale", "pasta, zucchine, melanzane, pomodori, basilico"),
    ("Polpettone di carne", "normale", "carne macinata, uova, pangrattato, prezzemolo"),
    ("Tagliata di manzo con rucola e parmigiano", "normale", "manzo, rucola, parmigiano, olio extravergine d'oliva"),
    ("Ravioli di ricotta e spinaci con burro e salvia", "normale", "ravioli, ricotta, spinaci, burro, salvia"),
    ("Crema di zucchine", "normale", "zucchine, patate, brodo vegetale, pepe"),
    ("Salmone grigliato con verdure", "normale", "salmone, zucchine, peperoni, olio extravergine d'oliva"),
    ("Spiedini di pollo e verdure", "normale", "pollo, peperoni, zucchine, cipolla"),
    ("Lasagna di verdure", "normale", "lasagne, zucchine, melanzane, pomodoro, besciamella"),
    ("Pasta con broccoli e acciughe", "normale", "pasta, broccoli, acciughe, aglio, peperoncino"),
    ("Pollo in padella con limone", "normale", "pollo, limone, rosmarino, aglio"),
    ("Crespelle con spinaci", "normale", "crespelle, spinaci, ricotta, parmigiano"),
    ("Frittata con erbe aromatiche", "normale", "uova, rosmarino, timo, prezzemolo"),
    ("Riso integrale con verdure", "normale", "riso integrale, zucchine, carote, peperoni, olio"),
    ("Pesce spada alla griglia", "normale", "pesce spada, limone, prezzemolo, olio d'oliva"),
    ("Vellutata di pomodoro", "normale", "pomodori, cipolla, basilico, brodo vegetale"),
    ("Insalata di pollo e quinoa", "normale", "pollo, quinoa, pomodorini, cetrioli, olio"),
    ("Polenta con sugo di funghi", "normale", "polenta, funghi, pomodoro, aglio"),
]


cursor.executemany("""
INSERT INTO ricette (nome, categoria, ingredienti)
VALUES (?, ?, ?);
""", ricette_predefinite)

# Commit delle operazioni e chiusura della connessione
conn.commit()
conn.close()

print("Database creato e popolato con successo!")
